### ISSUE TITLE
Error: Error building site: POSTCSS:

### ISSUE THREAD

**Issue by r1chy5** [tylersayshi/port-hugo#2]
Hello,

I went to test the theme and I get this error: 

`Error: Error building the site: POSTCSS: failed to transform "css/style.css" (text/css). Check your PostCSS installation; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/: this feature is not available in your current version of Hugo, see https://goo.gl/YMrWcn for more information.`

This is my version of Hugo:

`hugo v0.100.0-27b077544d8efeb85867cb4cfb941747d104f765+extended linux/amd64 BuildDate=2022-05-31T08:37:12Z VendorInfo=gohugoio`

In some forums I have seen that the solution is to install `postcss-cli`, this is so, I don't want to fill my machine with more packages.

Can you help me.

Kind regards

**Comment by tylersayshi** [comment]
How are you going about testing the theme? 

If you are just using the theme as is without trying to make new changes to it you'll be able to use the already generated stylesheets and postcss won't need to be installed or run. 

If you are trying to make style changes to the theme you will either need to change the way the styles are generated to not include postcss or install the package. The readme has instructions for how to develop the theme with the packages that it is designed to use.

**Comment by r1chy5** [comment]
Hello, 

What I'm doing is cloning the git, my intention is not to modify it, just use it and that's it. 

I find myself looking for hugo themes and I think this one has everything I'm looking for.

I have followed the steps in the readme, and I have found this error, not if you can help me, because I do not know if it is my mistake, or the code, or something.

Kind regards

**Comment by tylersayshi** [comment]
So I just tested this locally by setting it up from scratch and it seems that the `resources` needed to be regenerated. If you pull the latest changes into your clone of the theme, then recopy everything from `port-hugo/exampleSite` to the root of your project, it should run smoothly.

Something like this:
```sh
# starting from root of your project directory
cd themes/port-hugo
git pull
cd ..
cp -r themes/port-hugo/exampleSite/* .
hugo server
```

**Comment by r1chy5** [comment]
I have tested it and now it works, everything works perfectly.
Thanks
