### ISSUE TITLE
Home Page isn't Added During Build

### ISSUE THREAD

**Issue by loo3y35** [tylersayshi/port-hugo#5]
I'm testing with `hugo server` and `hugo` commands but both don't seem to build a home page
Here's an example of the public directory for the example site after `hugo` command
> user@PC % ls
> categories	images		index.xml	sitemap.xml	tags

Other themes are working fine, so I really doubt the issue is with hugo

A sample of a warning I get when running `hugo server` command is shown below
> WARN found no layout file for "HTML" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

Thanks!

**Comment by tylersayshi** [comment]
This is a duplicate of #4 - I'll respond there
