### ISSUE TITLE
Logo issues

### ISSUE THREAD

**Issue by SuperJMN** [tylersayshi/port-hugo#8]
Hello! Great theme!

An issue, though:

For me, using Chromium Based navigator, the logo shows a "broken image" icon unless I scroll down. It's then when it loads it.
On mobile, it always shows the broken icon.

![image](https://github.com/user-attachments/assets/4bacbe06-2bb0-473a-ab6a-98f74b8bf53a)

**Comment by tylersayshi** [comment]
@SuperJMN I'll check the demo, but in case that is working could you link the repo where this is broken for you?

**Comment by tylersayshi** [comment]
@SuperJMN you'll need to set the following in your config.toml:

```toml
[params]
logo_light = "images/logo.svg"
logo_dark = "images/logo-dark.svg"
```

If this solves the issue for you, would you mind submitting a PR to update the `exampleSite` in this repo if you have time?

Let me know if you have any other problems :)

**Comment by SuperJMN** [comment]
> @SuperJMN you'll need to set the following in your config.toml:
> 
> ```toml
> [params]
> logo_light = "images/logo.svg"
> logo_dark = "images/logo-dark.svg"
> ```
> 
> If this solves the issue for you, would you mind submitting a PR to update the `exampleSite` in this repo if you have time?
> 
> Let me know if you have any other problems :)

Thanks! I've linked a PR with the fix
